### Read / Write / Input Revision

In [1]:
import os
print(os.getcwd())

C:\Users\David Chia\Desktop\Analytics Revision - Sem 1 - 051026\smartphone-learning-analysis\notebooks

In [2]:
log_text = 'Project started.\nDataset: Students Smartphone Usage\nAUthor: David' 
#Creates file in code folder

with open('project_log.txt', 'w') as f:
    f.write(log_text)
print('log file written!')

log file written!

In [3]:
with open('project_log.txt','r') as b:
     contents = b.read()
print (contents)
print (type(contents))

Project started.
Dataset: Students Smartphone Usage
AUthor: David
<class 'str'>

In [4]:
student_name = input('Type your name: ')
message = 'Hello ' + student_name + ', let us explore thr smartphone dataset!'
print (message)

Type your name:  Brador

Hello Brador, let us explore thr smartphone dataset!

### Concatenation

In [5]:
first_name = student_name
course = 'IPDS'

greeting = 'Hi ' + first_name + ', welcone to ' + course + '!'
print(greeting)

Hi Brador, welcone to IPDS!

In [6]:
daily_hours = 3
#print ('Average daily usage: ' + daily_hours + ' hours')
print ('Average daily usage: ' + str(daily_hours) + ' hours')

Average daily usage: 3 hours

### If / Else

In [7]:
daily_usage = 4.6

if daily_usage < 1:
    category = 'Low usage'
elif daily_usage < 3:
    category = 'Moderate usage'
else:
    category = 'High usage'

print('Daily usage:', daily_usage, 'hours ->', category)

Daily usage: 4.6 hours -> High usage

In [8]:
helpful_for_study = 'Yes'

if helpful_for_study == 'Yes':
    print('This student find their phone helpfil for studying.')
else:
    print('This student does NOT find their phone helpful for studying.')

This student find their phone helpfil for studying.

### Lists

In [18]:
usage_hours = [2.0, 1.1, 0.3, 4.6, 3.9, 0.8]

print(usage_hours)
print(type(usage_hours))
print('Number of students in this list:', len(usage_hours), "tested students", len(usage_hours))

[2.0, 1.1, 0.3, 4.6, 3.9, 0.8]
<class 'list'>
Number of students in this list: 6 tested students 6

#### Slicing

In [19]:
print('Highest usage:', max(usage_hours))

Highest usage: 4.6

In [23]:
print('Lowest usage:', min(usage_hours))
print('Total hours:', sum(usage_hours))
print('Average hours:', sum(usage_hours) / len(usage_hours))

average_hours = sum(usage_hours) / len(usage_hours)
print(f"Average hours (rounded off): ${average_hours:.2f}")

Lowest usage: 0.3
Total hours: 12.7
Average hours: 2.1166666666666667
Average hours (rounded off): $2.12

#### Indexing and slicing

In [25]:
print(usage_hours[0]) # first item
print(usage_hours[-1]) # last item
print(usage_hours[1:4]) # a slice

2.0
0.8
[1.1, 0.3, 4.6]

#### Append

In [26]:
print(usage_hours)
usage_hours.append(3.8)
print(usage_hours)

[2.0, 1.1, 0.3, 4.6, 3.9, 0.8]
[2.0, 1.1, 0.3, 4.6, 3.9, 0.8, 3.8]

In [27]:
print(usage_hours)
usage_hours.pop()
print(usage_hours)

[2.0, 1.1, 0.3, 4.6, 3.9, 0.8, 3.8]
[2.0, 1.1, 0.3, 4.6, 3.9, 0.8]

In [28]:
usage_hours.append(2.7)

In [29]:
print(usage_hours)

[2.0, 1.1, 0.3, 4.6, 3.9, 0.8, 2.7]

### Dictionaries

In [30]:
student_record = {
    'Name' : 'Olivia',
    'Age' : 17,
    'Mobile Operating System' : 'iOS',
    'Daily usages' : 0.3,
    'Performance' : 'Good'
}

print(student_record)

{'Name': 'Olivia', 'Age': 17, 'Mobile Operating System': 'iOS', 'Daily usages': 0.3, 'Performance': 'Good'}

In [31]:
print(student_record['Daily usages'])

0.3

In [32]:
student_record['Helpful for studying'] = 'Yes' #TYPE THIS TO SIMPLY ADD A NEW UNIQUE KEY AND VALUE
print(student_record)

{'Name': 'Olivia', 'Age': 17, 'Mobile Operating System': 'iOS', 'Daily usages': 0.3, 'Performance': 'Good', 'Helpful for studying': 'Yes'}

### NumPy Arrays

In [39]:
import numpy as np
print(np.__version__)

2.3.5

In [40]:
# WITH ARRAY 1
usage_array = np.array(usage_hours)
print(usage_array)
print(type(usage_array))

[2.  1.1 0.3 4.6 3.9 0.8 2.7]
<class 'numpy.ndarray'>

#### No NumPy

In [44]:
#FOR LOOP SEARCH ITEMS DIRECTLY
total = 0
for h in usage_hours:
    total = total + h
    total = round(total,1)
    print(total)
mean = total / len(usage_hours)
print ('Final Mean: ', mean)

2.0
3.1
3.4
8.0
11.9
12.7
15.4
Final Mean:  2.2

In [45]:
#FOR LOOP SEARCH ITEMS OVER INDEXED POSITIONS
usage_hours = [2.0, 1.1, 0.3, 4.6, 3.9, 0.8, 2.7]
print(usage_hours)

[2.0, 1.1, 0.3, 4.6, 3.9, 0.8, 2.7]

In [48]:
for i in range(len(usage_hours)):
    total = total + usage_hours[i]

mean = total / len(usage_hours)
print(f"For Mean: ${mean:.2f}")

For Mean: $6.60

In [52]:
#While Loop
i=0
while i < len(usage_hours):
    total = total + usage_hours[i]
    i = i + 1
    print(i) # i will not show if not reset to 0 in the beginning
    
mean = total / len(usage_hours)
mean = round(mean,1)
print("While Mean :", mean)

1
2
3
4
5
6
7
While Mean : 15.4

In [53]:
# WITH ARRAY 2
print('Mean:', usage_array.mean())
print('Max:', usage_array.max())
print('Min:', usage_array.min())
print('Standard deviation:', round(usage_array.std(),2))

Mean: 2.2
Max: 4.6
Min: 0.3
Standard deviation: 1.5

In [54]:
#CONVERT HOURS TO MINUTES
usage_minutes = usage_array*60
print(usage_minutes)

[120.  66.  18. 276. 234.  48. 162.]

In [55]:
#BOOLEAN INDEXING
truth_table = usage_array > 3
print(truth_table)

[False False False  True  True False False]

In [56]:
heavy_users = usage_array[truth_table] #INPUT TRUTH TABLE RESULTS
print('Heavy users (>3 hrs):', heavy_users)

Heavy users (>3 hrs): [4.6 3.9]

### Dataframes

In [57]:
import pandas as pd
print(pd.__version__)

2.3.3

In [58]:
#Import .csv into a dataframe
df = pd.read_csv('../data/Impact_of_Mobile_Phone_on_Students_Health.csv')
df.head() #First 5 rows

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
0,Ali,21-25,Male,Yes,Android,Sometimes,Social Media,Yes,Educational Videos,4-6 hours,Agree,During Exams,Yes,Camera,Yes,Accounting,Headache,Never,Using Blue light filter,Excellent
1,Bilal,21-25,Male,Yes,Android,Sometimes,Social Media,Yes,Educational Videos,4-6 hours,Neutral,During Exams,Yes,Notes Taking App,Yes,Browsing Material,All of these,Sometimes,Taking Break during prolonged use,Good
2,Hammad,21-25,Male,Yes,IOS,Sometimes,All of these,Yes,Educational Videos,4-6 hours,Strongly agree,Not Distracting,No,Camera,Yes,Browsing Material,All of these,Sometimes,None of Above,Excellent
3,Abdullah,21-25,Male,Yes,Android,Frequently,All of these,Yes,Educational Videos,2-4 hours,Strongly agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,NaN,Never,Limiting Screen Time,Excellent
4,Waqar,21-25,Male,Yes,IOS,Frequently,All of these,Yes,Educational Videos,> 6 hours,Agree,While Studying,Yes,Internet Access,No,Browsing Material,Sleep disturbance,Sometimes,None of Above,Excellent

In [60]:
# Quick Inspection
print(df.shape) # how many columns and rows?
df.info() # check the dataset

(100, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Names                           100 non-null    object
 1   Age                             100 non-null    object
 2   Gender                          100 non-null    object
 3   Mobile Phone                    100 non-null    object
 4   Mobile Operating System         100 non-null    object
 5   Mobile phone use for education  98 non-null     object
 6   Mobile phone activities         99 non-null     object
 7   Helpful for studying            98 non-null     object
 8   Educational Apps                98 non-null     object
 9   Daily usages                    99 non-null     object
 10  Performance impact              98 non-null     object
 11  Usage distraction               98 non-null     object
 12  Attention span                  99 non-null     object
 13  Useful features                 98 non-null     object
 14  Health Risks                    98 non-null     object
 15  Beneficial subject              99 non-null     object
 16  Usage symptoms                  98 non-null     object
 17  Symptom frequency               99 non-null     object
 18  Health precautions              99 non-null     object
 19  Health rating                   99 non-null     object
dtypes: object(20)
memory usage: 15.8+ KB

In [61]:
df.describe() #Sumary numbers for each column

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
count,100,100,100,100,100,98,99,98,98,99,98,98,99,98,98,99,98,99,99,99
unique,100,4,2,1,2,4,7,2,4,4,5,4,2,4,3,3,6,4,4,7
top,Ali,21-25,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,4-6 hours,Agree,While Studying,Yes,Internet Access,Yes,Reasarch,All of these,Sometimes,Limiting Screen Time,Good
freq,1,72,81,100,81,53,59,94,54,40,40,34,70,70,57,48,32,52,35,42

In [62]:
#print(df['Daily usages'].mean())
#print(df['Mobile Operating System'].value_counts())

print(df['Daily usages'].dtype)

object

#### Cleaned data "smartphone-learning-analysis\data\Impact_of_Mobile_Phone_on_Students_Health_Cleaned"

In [63]:
df2 = pd.read_csv('../data/Impact_of_Mobile_Phone_on_Students_Health_Cleaned.csv')
df2.head() #First 5 rows

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
0,Abdullah,23,Male,Yes,Android,Frequently,All of these,Yes,Educational Videos,3.0,Strongly agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,NaN,Never,Limiting Screen Time,Excellent
1,Waqar,23,Male,Yes,IOS,Frequently,All of these,Yes,Educational Videos,7.0,Agree,While Studying,Yes,Internet Access,No,Browsing Material,Sleep disturbance,Sometimes,None of Above,Excellent
2,Aammar,23,Male,Yes,Android,Rarely,All of these,Yes,Educational Videos,7.0,Neutral,Not Distracting,Yes,Internet Access,Only Partially,Reasarch,Headache,Sometimes,None of Above,Good
3,Fatima,23,Female,Yes,IOS,Sometimes,All of these,Yes,Study Planner,5.0,Agree,Not Distracting,Yes,Internet Access,No,Reasarch,Sleep disturbance,Sometimes,None of Above,Good
4,Shafiq,23,Male,Yes,Android,Sometimes,Social Media;All of these,Yes,Study Planner,5.0,Agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,Sleep disturbance,Sometimes,None of Above,Excellent

In [64]:
print(df2['Daily usages'].mean().round(2)) #Mean + Round off to 2 decimal places

4.68

In [65]:
print(df2.columns.tolist())

['Names', 'Age', 'Gender ', 'Mobile Phone ', 'Mobile Operating System ', 'Mobile phone use for education', 'Mobile phone activities', 'Helpful for studying', 'Educational Apps', 'Daily usages', 'Performance impact', 'Usage distraction', 'Attention span', 'Useful features', 'Health Risks', 'Beneficial subject', 'Usage symptoms', 'Symptom frequency', 'Health precautions', 'Health rating']

In [66]:
print(df2['Mobile Operating System '].value_counts())

Mobile Operating System
Android    81
IOS        19
Name: count, dtype: int64

In [67]:
df2[['Names', 'Age', 'Gender ', 'Mobile Phone ', 'Performance impact']].head()

      Names  Age Gender  Mobile Phone  Performance impact
0  Abdullah   23    Male           Yes     Strongly agree
1     Waqar   23    Male           Yes              Agree
2    Aammar   23    Male           Yes            Neutral
3    Fatima   23  Female           Yes              Agree
4    Shafiq   23    Male           Yes              Agree

In [68]:
df2.dropna() #Remove all NaN

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
1,Waqar,23,Male,Yes,IOS,Frequently,All of these,Yes,Educational Videos,7.0,Agree,While Studying,Yes,Internet Access,No,Browsing Material,Sleep disturbance,Sometimes,None of Above,Excellent
2,Aammar,23,Male,Yes,Android,Rarely,All of these,Yes,Educational Videos,7.0,Neutral,Not Distracting,Yes,Internet Access,Only Partially,Reasarch,Headache,Sometimes,None of Above,Good
3,Fatima,23,Female,Yes,IOS,Sometimes,All of these,Yes,Study Planner,5.0,Agree,Not Distracting,Yes,Internet Access,No,Reasarch,Sleep disturbance,Sometimes,None of Above,Good
4,Shafiq,23,Male,Yes,Android,Sometimes,Social Media;All of these,Yes,Study Planner,5.0,Agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,Sleep disturbance,Sometimes,None of Above,Excellent
5,Mubashir,23,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,3.0,Agree,During Class Lectures,Yes,Internet Access,Only Partially,Reasarch,Sleep disturbance,Sometimes,Limiting Screen Time,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Qasim,23,Male,Yes,Android,Never,All of these,Yes,Educational Videos,5.0,Disagree,During Class Lectures,Yes,Camera,Yes,Reasarch,Headache,Never,Using Blue light filter,Good
94,Fayaz,23,Male,Yes,Android,Rarely,Messaging,Yes,Educational Videos,5.0,Disagree,While Studying,Yes,Camera,Yes,Accounting,Sleep disturbance,Rarely,Using Blue light filter,Good
97,Iftikhar,23,Male,Yes,Android,Sometimes,All of these,No,Language,7.0,Neutral,During Exams,Yes,Calculator,No,Browsing Material,Sleep disturbance,Rarely,Limiting Screen Time,Excellent;Good;Fair;Poor
98,Ehman,23,Female,Yes,IOS,Frequently,Social Media;Web-browsing;Messaging;All of these,Yes,Educational Videos,5.0,Neutral,Not Distracting,Yes,Camera,Yes,Reasarch,Headache,Rarely,Taking Break during prolonged use,Fair
99,Hafeez,18,Male,Yes,Android,Sometimes,Social Media,Yes,Educational Videos,5.0,Strongly agree,During Class Lectures,No,Notes Taking App,No,Reasarch,Anxiety or Stress,Sometimes,Taking Break during prolonged use,Good

#### Filtering with Booleans

In [69]:
heavy_users_df2 = df2[df2['Daily usages'] > 3]
heavy_users_df2.head() #DISPLAYS FIRST 5

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
1,Waqar,23,Male,Yes,IOS,Frequently,All of these,Yes,Educational Videos,7.0,Agree,While Studying,Yes,Internet Access,No,Browsing Material,Sleep disturbance,Sometimes,None of Above,Excellent
2,Aammar,23,Male,Yes,Android,Rarely,All of these,Yes,Educational Videos,7.0,Neutral,Not Distracting,Yes,Internet Access,Only Partially,Reasarch,Headache,Sometimes,None of Above,Good
3,Fatima,23,Female,Yes,IOS,Sometimes,All of these,Yes,Study Planner,5.0,Agree,Not Distracting,Yes,Internet Access,No,Reasarch,Sleep disturbance,Sometimes,None of Above,Good
4,Shafiq,23,Male,Yes,Android,Sometimes,Social Media;All of these,Yes,Study Planner,5.0,Agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,Sleep disturbance,Sometimes,None of Above,Excellent
6,Asad,23,Male,Yes,Android,Sometimes,All of these,Yes,Educational Videos,5.0,Agree,During Class Lectures,Yes,Internet Access,Yes,Reasarch,Sleep disturbance,Sometimes,Limiting Screen Time,Good

#### Finding frequent use of phones helpful

In [70]:
frequent_and_helped = df2[
    (df2['Mobile phone use for education'] == 'Frequently') & # Both are True
    (df2['Helpful for studying'] == 'Yes')
]

print('Students who use their phone frequently for study AND find it helpfil: ', len(frequent_and_helped))

Students who use their phone frequently for study AND find it helpfil:  25

In [71]:
# average daily usage for each performance category
df2.groupby('Performance impact')['Daily usages'].mean().sort_values()

Performance impact
Agree                4.600000
Strongly disagree    4.600000
Disagree             4.714286
Neutral              4.793103
Strongly agree       4.833333
Name: Daily usages, dtype: float64

In [72]:
#average daily usage for each age group
df2.groupby('Age')['Daily usages'].mean().sort_values()

Age
33    3.400000
18    4.466667
23    4.774648
28    5.000000
Name: Daily usages, dtype: float64

In [73]:
df2.groupby('Age')['Daily usages'].min() #All the same doesn't mean much

Age
18    1.0
23    1.0
28    1.0
33    1.0
Name: Daily usages, dtype: float64

### Use of Smartphone relates to education performance?

In [75]:
df2 = pd.read_csv('../data/Impact_of_Mobile_Phone_on_Students_Health_Cleaned.csv')
summary=[]

for usage_level in df2['Mobile phone use for education'].unique():
    subset = df2[df2['Mobile phone use for education'] == usage_level]
    yes_count = len(subset[subset['Helpful for studying'] == 'Yes'])
    total = len(subset)
    percent_helpful = round((yes_count / total) * 100, 1) if total > 0 else 0

    if percent_helpful >= 70:
        verdict = 'Strongly helpful'
    elif percent_helpful >= 40:
        verdict = 'Somewhat helpful'
    else:
        verdict = 'Not very helpful'

    summary[usage_level] = {
        'students': total,
        'percent_found_helpful': percent_helpful,
        'verdict': verdict
    }

for level, result in summary.items():
    print(level, '->', result)

TypeError: list indices must be integers or slices, not str

In [76]:
df2 = pd.read_csv('../data/Impact_of_Mobile_Phone_on_Students_Health_Cleaned.csv')
print(df2['Mobile phone use for education'].unique())

['Frequently' 'Rarely' 'Sometimes' 'Never' nan]

In [77]:
usage_level = 'Frequently'
subset = df2[df2['Mobile phone use for education'] == usage_level]
subset.head()

,Names,Age,Gender,Mobile Phone,Mobile Operating System,Mobile phone use for education,Mobile phone activities,Helpful for studying,Educational Apps,Daily usages,Performance impact,Usage distraction,Attention span,Useful features,Health Risks,Beneficial subject,Usage symptoms,Symptom frequency,Health precautions,Health rating
0,Abdullah,23,Male,Yes,Android,Frequently,All of these,Yes,Educational Videos,3.0,Strongly agree,During Class Lectures,No,Internet Access,Only Partially,Reasarch,NaN,Never,Limiting Screen Time,Excellent
1,Waqar,23,Male,Yes,IOS,Frequently,All of these,Yes,Educational Videos,7.0,Agree,While Studying,Yes,Internet Access,No,Browsing Material,Sleep disturbance,Sometimes,None of Above,Excellent
11,Zeeshan,23,Male,Yes,Android,Frequently,All of these,Yes,Productivity Tools,7.0,Agree,Not Distracting,No,Internet Access,Yes,Browsing Material,All of these,Sometimes,Using Blue light filter,Excellent
13,Maryam,28,Female,Yes,Android,Frequently,All of these,Yes,Productivity Tools,5.0,Strongly agree,While Studying,Yes,Internet Access,Yes,Reasarch,All of these,Frequently,None of Above,Good
15,Mudassar,23,Male,Yes,Android,Frequently,All of these,Yes,Educational Videos,7.0,Strongly disagree,During Class Lectures,No,Internet Access,Yes,Reasarch,Sleep disturbance,Sometimes,Using Blue light filter,Excellent

In [81]:
summary = {}

for usage_level in df2['Mobile phone use for education'].unique():
    
    subset = df2[df2['Mobile phone use for education'] == usage_level]
    yes_count = len(subset[subset['Helpful for studying'] == 'Yes'])

    total = len(subset)
    percent_helpful = round( (yes_count/total) * 100, 1) if total > 0 else 0

    if percent_helpful >= 70:
        verdict = 'Strongly helpful'
    elif percent_helpful >= 40:
        verdict = 'Somewhat helpful'
    else:
        verdict = 'Not very helpful'

    summary[usage_level] = {
        'students': total,
        'percent_found_helpful': percent_helpful,
        'verdict': verdict
    }

for level, result in summary.items():
    print(level, '-->', result)

Frequently --> {'students': 25, 'percent_found_helpful': 100.0, 'verdict': 'Strongly helpful'}
Rarely --> {'students': 10, 'percent_found_helpful': 90.0, 'verdict': 'Strongly helpful'}
Sometimes --> {'students': 53, 'percent_found_helpful': 96.2, 'verdict': 'Strongly helpful'}
Never --> {'students': 10, 'percent_found_helpful': 70.0, 'verdict': 'Strongly helpful'}
nan --> {'students': 0, 'percent_found_helpful': 0, 'verdict': 'Not very helpful'}

In [82]:
cd smartphone-learning-analysis
git init
git add .
git commit -m "Initial commit: smartphone usage & learning analysis"
 
# Create an empty repository on github.com first, then:
git remote add origin https://github.com/chiazishengdavid-build/learning_with_mobile_phones/smartphone-learning-analysis.git
git branch -M main
git push -u origin main

SyntaxError: invalid syntax (1530319389.py, line 1)